### ISSUE TITLE
V dokumentaci chybí zmínka, že skript vyžaduje Python 2

### ISSUE THREAD

**Issue by alpatron** [MartinRybensky/blogcz2wp#2]
Snažil jsem se použít skript s interpretem Python 3 ale nastaly chyby při spouštění. Poté jsem zjistil, že je třeba skript spustit pomocí Python 2. Z důvodu, že Python 3 je dnes již standardem, se tato nepříjemnost velice pravděpodně může stát mnoha lidem.
Bylo by tudíž dobré přidat zmínku, že skript je vytvořen pro Python 2, do readme.

**Comment by MartinRybensky** [comment]
Dobrá připomínka, doplněno.

**Comment by Jimmi08** [comment]
Obom aspoň takto ďakujem, Python použitý prvý raz v živote, takže dokumentácia je v poriadku.
